//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ships_System.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accident
    {
        public int AccidentId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ShipId { get; set; }
        public Nullable<int> Area { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string Details { get; set; }
        public string CrewConequences { get; set; }
        public string CrewAction { get; set; }
        public Nullable<bool> IsReported { get; set; }
        public string ReportedTo { get; set; }
        public string CostalStateAction { get; set; }
    
        public virtual Ship Ship { get; set; }
    }
}
